import java.util.*;

/**
 * Represents an order book that maintains buy and sell sides and processes incoming orders.
 * It supports both limit and iceberg orders.
 */
public class OrderBook {
    // Buy side (Price DESC)
    private TreeMap<Integer, ArrayDeque<Order>> buySide = new TreeMap<>(Collections.reverseOrder());
    
    // Sell side (Price ASC)
    private TreeMap<Integer, ArrayDeque<Order>> sellSide = new TreeMap<>();
    
    /**
     * Adds an order to the book and processes any matches against the opposite side.
     *
     * @param incomingOrder the order to be added
     * @return a list of trades generated by matching the incoming order
     */
    public List<Trade> addOrder(Order incomingOrder) {
        // 1. Process matches against the opposite side
        List<Trade> trades = processMatches(incomingOrder);

        // 2. Add remaining quantity to the book
        if (incomingOrder.getTotalQuantity() > 0) {
            if (incomingOrder.getSide() == 'B') {
                buySide.computeIfAbsent(incomingOrder.getPrice(), k -> new ArrayDeque<>()).addLast(incomingOrder);
            } else {
                sellSide.computeIfAbsent(incomingOrder.getPrice(), k -> new ArrayDeque<>()).addLast(incomingOrder);
            }
        }
        
        return trades;
    }

    /**
     * Processes matches for the incoming order against orders on the opposite side of the book.
     *
     * @param incomingOrder the order to match
     * @return a list of trades resulting from the matches
     */
    private List<Trade> processMatches(Order incomingOrder) {
        char side = incomingOrder.getSide();
        TreeMap<Integer, ArrayDeque<Order>> oppositeSide = determineOppositeSide(side);

        // Map to track total quantity matched against each existing order ID during this incomingOrder's match cycle.
        // Key: Order ID, Value: QuantityMatched
        Map<Integer, Integer> matchQuantities = new LinkedHashMap<>();
        Map<Integer, Integer> matchPrices = new HashMap<>();

        while (incomingOrder.getTotalQuantity() > 0 && !oppositeSide.isEmpty()) {
            Map.Entry<Integer, ArrayDeque<Order>> bestEntry = oppositeSide.firstEntry();
            int bestPrice = bestEntry.getKey();

            // Check if price matches
            if (!checkPriceMatch(side, incomingOrder.getPrice(), bestPrice)) break;

            ArrayDeque<Order> queue = bestEntry.getValue();
            Order existingOrder = queue.peekFirst();
            
            if (existingOrder == null) {
                oppositeSide.remove(bestPrice);
                continue;
            }

            int matchQty = Math.min(incomingOrder.getTotalQuantity(), existingOrder.getVisibleQuantity());
            if (matchQty > 0) {
                incomingOrder.reduceQuantity(matchQty);
                existingOrder.reduceQuantity(matchQty);
                
                matchQuantities.put(existingOrder.getId(), matchQuantities.getOrDefault(existingOrder.getId(), 0) + matchQty);
                matchPrices.put(existingOrder.getId(), bestPrice);
            }

            if (existingOrder.getVisibleQuantity() == 0) {
                queue.removeFirst();
                if (existingOrder.getTotalQuantity() > 0) {
                    existingOrder.replenish();
                    queue.addLast(existingOrder);
                }
            }

            if (queue.isEmpty()) {
                oppositeSide.remove(bestPrice);
            }
        }

        // Convert the match records into Trade objects
        return createTradesFromMatches(side, incomingOrder, matchQuantities, matchPrices);
    }

    // Public methods for retrieving book rows
    public List<BookRow> getBuyRows() {
        return createBookRows(buySide);
    }

    public List<BookRow> getSellRows() {
        return createBookRows(sellSide);
    }

    /**
     * Creates book rows from the given side of the order book.
     *
     * @param orderSide the TreeMap representing one side of the book
     * @return a list of {@link BookRow} objects
     */
    private List<BookRow> createBookRows(TreeMap<Integer, ArrayDeque<Order>> orderSide) {
        List<BookRow> rows = new ArrayList<>();
        for (Map.Entry<Integer, ArrayDeque<Order>> entry : orderSide.entrySet()) {
            for (Order o : entry.getValue()) {
                rows.add(new BookRow(o.getId(), o.getVisibleQuantity(), entry.getKey()));
            }
        }
        return rows;
    }

    // Private helpers for testing
    public int getBuyOrderCount(int price) {
        return buySide.containsKey(price) ? buySide.get(price).size() : 0;
    }

    public int getSellOrderCount(int price) {
        return sellSide.containsKey(price) ? sellSide.get(price).size() : 0;
    }

    /**
     * Determines which side of the book is opposite to the given side.
     *
     * @param side 'B' for buy, 'S' for sell
     * @return the TreeMap of the opposite side
     */
    private TreeMap<Integer, ArrayDeque<Order>> determineOppositeSide(char side) {
        return (side == 'B') ? sellSide : buySide;
    }

    /**
     * Checks if the incoming order's price matches the best price on the opposite side.
     *
     * @param side the side of the incoming order
     * @param incomingOrderPrice the price of the incoming order
     * @param bestPrice the best price currently available on the opposite side
     * @return true if there is a price overlap, false otherwise
     */
    private boolean checkPriceMatch(char side, int incomingOrderPrice, int bestPrice) {
        if (side == 'B' && incomingOrderPrice < bestPrice) return false;
        if (side == 'S' && incomingOrderPrice > bestPrice) return false;
        return true;
    }

    /**
     * Creates Trade objects from the accumulated match information.
     *
     * @param side the side of the incoming order
     * @param incomingOrder the incoming order
     * @param matchQuantities a map of existing order IDs to matched quantities
     * @param matchPrices a map of existing order IDs to match prices
     * @return a list of generated {@link Trade} objects
     */
    private List<Trade> createTradesFromMatches(char side, Order incomingOrder, Map<Integer, Integer> matchQuantities, Map<Integer, Integer> matchPrices) {
        List<Trade> trades = new ArrayList<>();
        for (Integer existingOrderId : matchQuantities.keySet()) {
            int qty = matchQuantities.get(existingOrderId);
            int price = matchPrices.get(existingOrderId);

            if (side == 'B') {
                trades.add(new Trade(incomingOrder.getId(), existingOrderId, price, qty));
            } else {
                trades.add(new Trade(existingOrderId, incomingOrder.getId(), price, qty));
            }
        }
        return trades;
    }
}