import java.util.*;

/**
 * Represents an order book that maintains buy and sell sides and processes incoming orders.
 * It supports both limit and iceberg orders.
 */
public class OrderBook {
    // price : Queue[OrderID]  Buy side (Price DESC)
    private TreeMap<Integer, ArrayDeque<Order>> buySide = new TreeMap<>(Collections.reverseOrder());

    // price : Queue[OrderID]  Sell side (Price ASC)
    private TreeMap<Integer, ArrayDeque<Order>> sellSide = new TreeMap<>();

    /**
     * Adds an order to the book and processes any matches against the opposite side.
     *
     * @param incomingOrder the order to be added
     * @return a list of trades generated by matching the incoming order
     */
    public List<Trade> addOrder(Order incomingOrder) {

        List<Trade> trades = processMatches(incomingOrder);

        // Add remaining quantity to the book if it has remaining quantity after matching
        if (incomingOrder.getTotalQuantity() > 0) {
            if (incomingOrder.getSide() == 'B') {
                buySide.computeIfAbsent(incomingOrder.getPrice(), k -> new ArrayDeque<>()).addLast(incomingOrder);
            } else {
                sellSide.computeIfAbsent(incomingOrder.getPrice(), k -> new ArrayDeque<>()).addLast(incomingOrder);
            }
        }

        return trades;
    }

    /**
     * Processes matches for the incoming order against orders on the opposite side of the book.
     *
     * @param incomingOrder the order to match
     * @return a list of trades resulting from the matches
     */
    private List<Trade> processMatches(Order incomingOrder) {
        char side = incomingOrder.getSide();
        TreeMap<Integer, ArrayDeque<Order>> oppositeSide = determineOppositeSide(side);

        // Order ID: QuantityMatched
        Map<Integer, Integer> matchQuantities = new LinkedHashMap<>();
        // Order ID: Price
        Map<Integer, Integer> matchPrices = new HashMap<>();

        while (incomingOrder.getTotalQuantity() > 0 && !oppositeSide.isEmpty()) {
            Map.Entry<Integer, ArrayDeque<Order>> bestEntry = oppositeSide.firstEntry();
            int bestPrice = bestEntry.getKey();

            if (!checkPriceOverlap(side, incomingOrder.getPrice(), bestPrice)) break;

            ArrayDeque<Order> queue = bestEntry.getValue();
            Order existingOrder = queue.peekFirst();

            if (existingOrder == null) {
                oppositeSide.remove(bestPrice);
                continue;
            }

            int incomingVisible = incomingOrder.getVisibleQuantity();
            int existingVisible = existingOrder.getVisibleQuantity();
            int matchQuantity = Math.min(incomingVisible, existingVisible);

            // No visible quantity, try to replenish (iceberg)
            if (matchQuantity == 0) {
                if (incomingVisible == 0 && incomingOrder.getTotalQuantity() > 0) incomingOrder.replenish();
                // Existing order needs to be added to back of queue if it has remaining quantity
                if (existingVisible == 0 && existingOrder.getTotalQuantity() > 0) {
                    queue.removeFirst();
                    existingOrder.replenish();
                    queue.addLast(existingOrder);
                // Remove empty order
                } else if (existingVisible == 0) {
                    queue.removeFirst();
                }

                if (queue.isEmpty()) oppositeSide.remove(bestPrice);
                break;
            }

            // Execute match
            incomingOrder.reduceQuantity(matchQuantity);
            existingOrder.reduceQuantity(matchQuantity);

            matchQuantities.put(existingOrder.getId(),
                    matchQuantities.getOrDefault(existingOrder.getId(), 0) + matchQuantity);
            matchPrices.put(existingOrder.getId(), bestPrice);

            // Handle resting order depletion / replenish
            if (existingOrder.getVisibleQuantity() == 0) {
                queue.removeFirst();
                if (existingOrder.getTotalQuantity() > 0) {
                    existingOrder.replenish();
                    queue.addLast(existingOrder);
                }
            }

            // Handle incoming order replenish
            if (incomingOrder.getVisibleQuantity() == 0 && incomingOrder.getTotalQuantity() > 0) {
                incomingOrder.replenish();
            }

            // Clean up empty price levels
            if (queue.isEmpty()) {
                oppositeSide.remove(bestPrice);
            }
        }

        return createTradesFromMatches(side, incomingOrder, matchQuantities, matchPrices);
    }

    public List<BookRow> getBuyRows() {
        return createBookRows(buySide);
    }

    public List<BookRow> getSellRows() {
        return createBookRows(sellSide);
    }

    /**
     * Creates book rows from the given side of the order book.
     *
     * @param orderSide the TreeMap representing one side of the book
     * @return a list of {@link BookRow} objects
     */
    private List<BookRow> createBookRows(TreeMap<Integer, ArrayDeque<Order>> orderSide) {
        List<BookRow> rows = new ArrayList<>();
        for (Map.Entry<Integer, ArrayDeque<Order>> entry : orderSide.entrySet()) {
            for (Order o : entry.getValue()) {
                rows.add(new BookRow(o.getId(), o.getVisibleQuantity(), entry.getKey()));
            }
        }
        return rows;
    }

    // Private helpers for testing
    public int getBuyOrderCount(int price) {
        return buySide.containsKey(price) ? buySide.get(price).size() : 0;
    }

    public int getSellOrderCount(int price) {
        return sellSide.containsKey(price) ? sellSide.get(price).size() : 0;
    }

    /**
     * Determines which side of the book is opposite to the given side.
     *
     * @param side 'B' for buy, 'S' for sell
     * @return the TreeMap of the opposite side
     */
    private TreeMap<Integer, ArrayDeque<Order>> determineOppositeSide(char side) {
        return (side == 'B') ? sellSide : buySide;
    }

    /**
     * Checks if the incoming order's price matches the best price on the opposite side.
     *
     * @param side the side of the incoming order
     * @param incomingOrderPrice the price of the incoming order
     * @param bestPrice the best price currently available on the opposite side
     * @return true if there is a price overlap, false otherwise
     */
    private boolean checkPriceOverlap(char side, int incomingOrderPrice, int bestPrice) {
        if (side == 'B' && incomingOrderPrice < bestPrice) return false;
        if (side == 'S' && incomingOrderPrice > bestPrice) return false;
        return true;
    }

    /**
     * Creates Trade objects from the accumulated match information.
     *
     * @param side the side of the incoming order
     * @param incomingOrder the incoming order
     * @param matchQuantities a map of existing order IDs to matched quantities
     * @param matchPrices a map of existing order IDs to match prices
     * @return a list of generated {@link Trade} objects
     */
    private List<Trade> createTradesFromMatches(char side, Order incomingOrder, Map<Integer, Integer> matchQuantities, Map<Integer, Integer> matchPrices) {
        List<Trade> trades = new ArrayList<>();
        for (Integer existingOrderId : matchQuantities.keySet()) {
            int qty = matchQuantities.get(existingOrderId);
            int price = matchPrices.get(existingOrderId);

            if (side == 'B') {
                trades.add(new Trade(incomingOrder.getId(), existingOrderId, price, qty));
            } else {
                trades.add(new Trade(existingOrderId, incomingOrder.getId(), price, qty));
            }
        }
        return trades;
    }
}
