import java.util.*;
/**
 * Represents an order book that maintains buy and sell sides and processes incoming orders.
 * It supports both limit and iceberg orders.
 */
public class OrderBook {
    private static class MatchInfo {
        private int quantity;
        private int price;

        private MatchInfo(int quantity, int price) {
            this.quantity = quantity;
            this.price = price;
        }

        private void addQuantity(int matchQuantity) {
            this.quantity += matchQuantity;
        }
    }
    // price : Queue[OrderID]  Buy side (Price DESC)
    private TreeMap<Integer, ArrayDeque<Order>> buySide = new TreeMap<>(Collections.reverseOrder());

    // price : Queue[OrderID]  Sell side (Price ASC)
    private TreeMap<Integer, ArrayDeque<Order>> sellSide = new TreeMap<>();

    /**
     * Adds an order to the book and processes any matches against the opposite side.
     *
     * @param incomingOrder the order to be added
     * @return a list of trades generated by matching the incoming order
     */
    public List<Trade> addOrder(Order incomingOrder) {

        List<Trade> trades = processMatches(incomingOrder);

        // Add remaining quantity to the book if it has remaining quantity after matching
        if (incomingOrder.getTotalQuantity() > 0) {
            if (incomingOrder.getSide() == 'B') {
                buySide.computeIfAbsent(incomingOrder.getPrice(), k -> new ArrayDeque<>()).addLast(incomingOrder);
            } else {
                sellSide.computeIfAbsent(incomingOrder.getPrice(), k -> new ArrayDeque<>()).addLast(incomingOrder);
            }
        }

        return trades;
    }

    /**
     * Processes matches for the incoming order against orders on the opposite side of the book.
     *
     * @param incomingOrder the order to match
     * @return a list of trades resulting from the matches
     */
    private List<Trade> processMatches(Order incomingOrder) {
        char side = incomingOrder.getSide();
        // Sorted hashmap price : Queue[OrderID]
        TreeMap<Integer, ArrayDeque<Order>> oppositeSide = determineOppositeSide(side);
        // Ordered hashmap orderID : (quantity, price)
        Map<Integer, MatchInfo> matchInfoByOrderId = new LinkedHashMap<>();

        while (incomingOrder.getTotalQuantity() > 0 && !oppositeSide.isEmpty()) {
            Map.Entry<Integer, ArrayDeque<Order>> bestEntry = oppositeSide.firstEntry();
            int bestPrice = bestEntry.getKey();
            ArrayDeque<Order> queue = bestEntry.getValue();
            Order existingOrder = queue.peekFirst();

            if (!checkPriceOverlap(side, incomingOrder.getPrice(), bestPrice)) break;

            int incomingVisible = ensureVisibleQuantity(incomingOrder);
            int existingVisible = existingOrder.getVisibleQuantity();
            if (existingVisible == 0) {            
                if (queue.isEmpty()) oppositeSide.remove(bestPrice);
                continue; 
            }
            
            int matchQuantity = Math.min(incomingVisible, existingVisible);
            if (matchQuantity == 0) {
                continue;
            }

            // Execute match
            executeMatch(incomingOrder, existingOrder, matchQuantity, bestPrice, matchInfoByOrderId);

            handleIncomingReplenish(incomingOrder);
            handleExistingReplenish(queue, existingOrder);
            // Clean up empty price levels
            if (queue.isEmpty()) {
                oppositeSide.remove(bestPrice);
            }
        }

        return createTradesFromMatches(side, incomingOrder, matchInfoByOrderId);
    }

    public List<BookRow> getBuyRows() {
        return createBookRows(buySide);
    }

    public List<BookRow> getSellRows() {
        return createBookRows(sellSide);
    }

    /**
     * Creates book rows from the given side of the order book.
     *
     * @param orderSide the TreeMap representing one side of the book
     * @return a list of {@link BookRow} objects
     */
    private List<BookRow> createBookRows(TreeMap<Integer, ArrayDeque<Order>> orderSide) {
        List<BookRow> rows = new ArrayList<>();
        for (Map.Entry<Integer, ArrayDeque<Order>> entry : orderSide.entrySet()) {
            for (Order o : entry.getValue()) {
                rows.add(new BookRow(o.getId(), o.getVisibleQuantity(), entry.getKey()));
            }
        }
        return rows;
    }

    // Private helpers for testing
    public int getBuyOrderCount(int price) {
        return buySide.containsKey(price) ? buySide.get(price).size() : 0;
    }

    public int getSellOrderCount(int price) {
        return sellSide.containsKey(price) ? sellSide.get(price).size() : 0;
    }

    /**
     * Determines which side of the book is opposite to the given side.
     *
     * @param side 'B' for buy, 'S' for sell
     * @return the TreeMap of the opposite side
     */
    private TreeMap<Integer, ArrayDeque<Order>> determineOppositeSide(char side) {
        return (side == 'B') ? sellSide : buySide;
    }

    /**
     * Ensures the order has a visible quantity if it has remaining total quantity.
     *
     * @param order the order to update
     * @return the visible quantity after any replenishment
     */
    private int ensureVisibleQuantity(Order order) {
        if (order.getVisibleQuantity() == 0 && order.getTotalQuantity() > 0) {
            order.replenish();
        }
        return order.getVisibleQuantity();
    }

    /**
     * Executes the match by updating quantities and recording match information.
     *
     * @param incomingOrder      the incoming order
     * @param existingOrder      the existing order being matched against
     * @param matchQuantity      the quantity to match
     * @param price              the execution price
     * @param matchInfoByOrderId the map to record match details
     */
    private void executeMatch(Order incomingOrder, Order existingOrder, int matchQuantity, int price, Map<Integer, MatchInfo> matchInfoByOrderId) {
        incomingOrder.reduceQuantity(matchQuantity);
        existingOrder.reduceQuantity(matchQuantity);

        MatchInfo matchInfo = matchInfoByOrderId.get(existingOrder.getId());
        if (matchInfo == null) {
            matchInfo = new MatchInfo(0, price);
            matchInfoByOrderId.put(existingOrder.getId(), matchInfo);
        }
        matchInfo.addQuantity(matchQuantity);
        matchInfo.price = price;
    }

    /**
     * Handles depletion and potential replenishment for an existing order at a price level.
     *
     * @param queue the price level queue
     * @param existingOrder the existing order to update
     */
    private void handleExistingReplenish(ArrayDeque<Order> queue, Order existingOrder) {
        if (existingOrder.getVisibleQuantity() == 0) {
            queue.removeFirst();
            if (existingOrder.getTotalQuantity() > 0) {
                existingOrder.replenish();
                queue.addLast(existingOrder);
            }
        }
    }

    /**
     * Handles replenishment for the incoming order when its visible quantity is depleted.
     *
     * @param incomingOrder the incoming order to update
     */
    private void handleIncomingReplenish(Order incomingOrder) {
        if (incomingOrder.getVisibleQuantity() == 0 && incomingOrder.getTotalQuantity() > 0) {
            incomingOrder.replenish();
        }
    }

    /**
     * Checks if the incoming order's price matches the best price on the opposite side.
     *
     * @param side the side of the incoming order
     * @param incomingOrderPrice the price of the incoming order
     * @param bestPrice the best price currently available on the opposite side
     * @return true if there is a price overlap, false otherwise
     */
    private boolean checkPriceOverlap(char side, int incomingOrderPrice, int bestPrice) {
        if (side == 'B' && incomingOrderPrice < bestPrice) return false;
        if (side == 'S' && incomingOrderPrice > bestPrice) return false;
        return true;
    }

    /**
     * Creates Trade objects from the accumulated match information.
     *
     * @param side the side of the incoming order
     * @param incomingOrder the incoming order
     * @param matchInfoByOrderId a map of existing order IDs to matched info
     * @return a list of generated {@link Trade} objects
     */
    private List<Trade> createTradesFromMatches(char side, Order incomingOrder, Map<Integer, MatchInfo> matchInfoByOrderId) {
        List<Trade> trades = new ArrayList<>();
        for (Map.Entry<Integer, MatchInfo> entry : matchInfoByOrderId.entrySet()) {
            Integer existingOrderId = entry.getKey();
            MatchInfo matchInfo = entry.getValue();
            int qty = matchInfo.quantity;
            int price = matchInfo.price;

            if (side == 'B') {
                trades.add(new Trade(incomingOrder.getId(), existingOrderId, price, qty));
            } else {
                trades.add(new Trade(existingOrderId, incomingOrder.getId(), price, qty));
            }
        }
        return trades;
    }
}